### ISSUE TITLE
yarn3 indicating a missing peer dependency of typescript.

### ISSUE THREAD

**Issue by verikono** [lightyen/typescript-paths#6]
Hi!

Thanks so much for your effort here!

I'm getting an downstream effect via @graphql-codegen/cli on yarn3.

```rollup-plugin-tsconfig-paths@npm:1.4.0 [3bb2f] doesn't provide typescript (p6dbbd), requested by typescript-paths```

this is certainly no show stopper but i thought i'd mention it - i *believe* this should be as simple as adding your typescript version as a peer dependency in package.json.

Have a great day , and thanks again!

**Comment by lightyen** [comment]
I am not familiar with yarn3. But I think yarn3 is more strict than npm/pnpm, you can add peerDependencies to `packageExtensions` in .yarnrc.yml:
```yaml
packageExtensions:
  rollup-plugin-tsconfig-paths@*:
    peerDependencies:
      typescript: "*"
```
